/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NoteReviewerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  sectionOrder: ["Overdue", "Today", "Stage"],
  presets: [
    {
      name: "standard",
      intervals: [1, 3, 7, 15, 30, 60, 120],
      repeatInterval: 120
    },
    {
      name: "concept",
      intervals: [1, 3, 10, 30, 60, 120],
      repeatInterval: 120
    },
    {
      name: "hard",
      intervals: [1, 2, 4, 8, 14, 21, 30, 45],
      repeatInterval: 60
    }
  ]
};
var FRONTMATTER_KEYS = {
  REVIEW: "review",
  NEXT_DATE: "review-next-date",
  INTERVAL_INDEX: "review-interval-index",
  SKIP_COUNT: "review-skip-count"
};

// src/settings/SettingsTab.ts
var import_obsidian = require("obsidian");
var SettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Note Reviewer Settings" });
    containerEl.createEl("h3", { text: "Section Layout" });
    containerEl.createEl("p", {
      text: "Drag and drop to rearrange the sections in the Review Pane."
    });
    const listContainer = containerEl.createDiv("note-reviewer-drag-list");
    let draggedIndex = null;
    if (!this.plugin.settings.sectionOrder || this.plugin.settings.sectionOrder.length === 0) {
      this.plugin.settings.sectionOrder = ["Overdue", "Today", "Stage"];
    }
    this.plugin.settings.sectionOrder.forEach((sectionName, index) => {
      const itemEl = listContainer.createDiv("note-reviewer-drag-item");
      itemEl.setAttribute("draggable", "true");
      const contentEl = itemEl.createDiv();
      contentEl.style.display = "flex";
      contentEl.style.alignItems = "center";
      contentEl.style.gap = "8px";
      contentEl.createSpan({ text: "\u2630", cls: "note-reviewer-drag-handle" });
      contentEl.createSpan({ text: sectionName });
      itemEl.ondragstart = (e) => {
        draggedIndex = index;
        itemEl.addClass("is-dragging");
        if (e.dataTransfer)
          e.dataTransfer.effectAllowed = "move";
      };
      itemEl.ondragover = (e) => {
        e.preventDefault();
        if (e.dataTransfer)
          e.dataTransfer.dropEffect = "move";
        const draggingItem = listContainer.querySelector(".is-dragging");
        if (!draggingItem)
          return;
        const siblings = Array.from(listContainer.querySelectorAll(".note-reviewer-drag-item:not(.is-dragging)"));
        const nextSibling = siblings.find((sibling) => {
          const rect = sibling.getBoundingClientRect();
          return e.clientY <= rect.top + rect.height / 2;
        });
        if (nextSibling) {
          listContainer.insertBefore(draggingItem, nextSibling);
        } else {
          listContainer.appendChild(draggingItem);
        }
      };
      itemEl.ondrop = async (e) => {
        e.preventDefault();
        if (draggedIndex !== null) {
          const currentItems = Array.from(listContainer.querySelectorAll(".note-reviewer-drag-item"));
          const newIndex = currentItems.indexOf(itemEl);
          if (newIndex !== -1 && draggedIndex !== newIndex) {
            const newOrder = [...this.plugin.settings.sectionOrder];
            const [removed] = newOrder.splice(draggedIndex, 1);
            newOrder.splice(newIndex, 0, removed);
            this.plugin.settings.sectionOrder = newOrder;
            await this.plugin.saveSettings();
            this.app.workspace.getLeavesOfType("note-reviewer-view").forEach((leaf) => {
              if (leaf.view && typeof leaf.view.renderView === "function") {
                leaf.view.renderView();
              }
            });
          }
        }
      };
      itemEl.ondragend = () => {
        draggedIndex = null;
        itemEl.removeClass("is-dragging");
        this.display();
      };
    });
    containerEl.createEl("hr");
    containerEl.createEl("h3", { text: "Presets" });
    containerEl.createEl("p", {
      text: "Define presets that you can assign to your notes. In a note's frontmatter, set 'review: preset_name' to use it."
    });
    new import_obsidian.Setting(containerEl).setName("Add New Preset").setDesc("Create a new preset with default intervals").addButton((btn) => btn.setButtonText("Add").setCta().onClick(async () => {
      const newPresetName = `preset_${this.plugin.settings.presets.length + 1}`;
      this.plugin.settings.presets.push({
        name: newPresetName,
        intervals: [1, 3, 7, 14, 21, 30],
        repeatInterval: 60
      });
      await this.plugin.saveSettings();
      this.display();
    }));
    for (let i = 0; i < this.plugin.settings.presets.length; i++) {
      const preset = this.plugin.settings.presets[i];
      containerEl.createEl("h4", { text: `Preset: ${preset.name}` });
      new import_obsidian.Setting(containerEl).setName("Name").addText((text) => text.setValue(preset.name).onChange(async (val) => {
        preset.name = val;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("Intervals (days)").setDesc("Comma-separated list of days for spaced repetition").addText((text) => text.setValue(preset.intervals.join(", ")).onChange(async (val) => {
        const arr = val.split(",").map((s) => parseInt(s.trim())).filter((n) => !isNaN(n));
        preset.intervals = arr;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("Repeat Interval (days)").setDesc("Number of days to repeat after the last interval is reached").addText((text) => text.setValue(preset.repeatInterval.toString()).onChange(async (val) => {
        const num = parseInt(val.trim());
        if (!isNaN(num)) {
          preset.repeatInterval = num;
          await this.plugin.saveSettings();
        }
      }));
      new import_obsidian.Setting(containerEl).setName("Delete Preset").addButton((btn) => btn.setButtonText("Delete").setWarning().onClick(async () => {
        if (this.plugin.settings.presets.length === 1) {
          new import_obsidian.Notice("You must have at least one preset.");
          return;
        }
        this.plugin.settings.presets.splice(i, 1);
        await this.plugin.saveSettings();
        this.display();
      }));
      containerEl.createEl("hr");
    }
  }
};

// src/utils/DateUtils.ts
var DateUtils = class {
  /**
   * Returns today's date as a YYYY-MM-DD string.
   */
  static getTodayStr() {
    const date = /* @__PURE__ */ new Date();
    return this.formatDate(date);
  }
  /**
   * Formats a Date object to YYYY-MM-DD.
   */
  static formatDate(date) {
    const yyyy = date.getFullYear();
    const mm = String(date.getMonth() + 1).padStart(2, "0");
    const dd = String(date.getDate()).padStart(2, "0");
    return `${yyyy}-${mm}-${dd}`;
  }
  /**
   * Adds `days` to the given `dateStr` (YYYY-MM-DD) and returns the new date string.
   */
  static addDays(dateStr, days) {
    const date = new Date(dateStr);
    date.setDate(date.getDate() + days);
    return this.formatDate(date);
  }
  /**
   * Checks if `dateStr` (YYYY-MM-DD) is today or earlier.
   */
  static isDue(dateStr) {
    if (!dateStr)
      return true;
    const todayStr = this.getTodayStr();
    return dateStr <= todayStr;
  }
};

// src/review/ReviewManager.ts
var ReviewManager = class {
  constructor(app, settings, fmUtils) {
    this.app = app;
    this.settings = settings;
    this.fmUtils = fmUtils;
  }
  /**
   * Finds all notes that are due for review today or earlier.
   */
  getDueNotes() {
    const dueNotes = [];
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      const presetName = this.fmUtils.getReviewPreset(file);
      if (presetName) {
        const nextDate = this.fmUtils.getProperty(file, FRONTMATTER_KEYS.NEXT_DATE);
        if (DateUtils.isDue(nextDate)) {
          const intervalIndex = Number(this.fmUtils.getProperty(file, FRONTMATTER_KEYS.INTERVAL_INDEX)) || 0;
          dueNotes.push({ file, presetName, nextDate, intervalIndex });
        }
      }
    }
    dueNotes.sort((a, b) => {
      const dateA = a.nextDate || "";
      const dateB = b.nextDate || "";
      return dateA.localeCompare(dateB);
    });
    return dueNotes;
  }
  simulateDone(item) {
    const preset = this.getPreset(item.presetName);
    let currentIndex = Number(this.fmUtils.getProperty(item.file, FRONTMATTER_KEYS.INTERVAL_INDEX)) || 0;
    if (isNaN(currentIndex))
      currentIndex = 0;
    let daysToAdd = preset.repeatInterval;
    if (currentIndex < preset.intervals.length) {
      daysToAdd = preset.intervals[currentIndex];
    }
    const date = DateUtils.addDays(DateUtils.getTodayStr(), daysToAdd);
    return { date, daysToAdd };
  }
  /**
   * Mark a note as Done. Advance its interval index and set the next date.
   */
  async markDone(item) {
    const { date, daysToAdd } = this.simulateDone(item);
    let currentIndex = Number(this.fmUtils.getProperty(item.file, FRONTMATTER_KEYS.INTERVAL_INDEX)) || 0;
    if (isNaN(currentIndex))
      currentIndex = 0;
    await this.fmUtils.updateProperties(item.file, {
      [FRONTMATTER_KEYS.NEXT_DATE]: date,
      [FRONTMATTER_KEYS.INTERVAL_INDEX]: currentIndex + 1
    });
  }
  /**
   * Skip reviewing today. Act exactly like Done (advance date based on current interval),
   * but DO NOT increment the interval index. Instead, increment skip count.
   */
  async skipReview(item) {
    const { date } = this.simulateDone(item);
    let skipCount = Number(this.fmUtils.getProperty(item.file, FRONTMATTER_KEYS.SKIP_COUNT)) || 0;
    if (isNaN(skipCount))
      skipCount = 0;
    await this.fmUtils.updateProperties(item.file, {
      [FRONTMATTER_KEYS.NEXT_DATE]: date,
      [FRONTMATTER_KEYS.SKIP_COUNT]: skipCount + 1
      // Notice we do NOT update INTERVAL_INDEX
    });
  }
  /**
   * Postpone reviewing until tomorrow.
   */
  async postponeReview(item) {
    const nextDate = DateUtils.addDays(DateUtils.getTodayStr(), 1);
    await this.fmUtils.updateProperties(item.file, {
      [FRONTMATTER_KEYS.NEXT_DATE]: nextDate
    });
  }
  getLowestLoadDay(ignorePath) {
    const today = DateUtils.getTodayStr();
    const next7Days = [];
    for (let i = 1; i <= 7; i++) {
      next7Days.push(DateUtils.addDays(today, i));
    }
    const counts = {};
    for (const d of next7Days) {
      counts[d] = 0;
    }
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      if (file.path === ignorePath)
        continue;
      const nextDate = this.fmUtils.getProperty(file, FRONTMATTER_KEYS.NEXT_DATE);
      if (nextDate && counts[nextDate] !== void 0) {
        counts[nextDate]++;
      }
    }
    let lowestDay = next7Days[0];
    let lowestCount = counts[lowestDay];
    for (let i = 1; i < next7Days.length; i++) {
      const day = next7Days[i];
      if (counts[day] < lowestCount) {
        lowestCount = counts[day];
        lowestDay = day;
      }
    }
    const daysToAdd = next7Days.indexOf(lowestDay) + 1;
    return { date: lowestDay, daysToAdd };
  }
  /**
   * Adjust review to the day with the lowest number of notes in the next 7 days.
   */
  async adjustReview(item) {
    const { date } = this.getLowestLoadDay(item.file.path);
    await this.fmUtils.updateProperties(item.file, {
      [FRONTMATTER_KEYS.NEXT_DATE]: date
    });
  }
  getPreset(name) {
    const preset = this.settings.presets.find((p) => p.name === name);
    if (preset)
      return preset;
    return this.settings.presets[0] || {
      name: "standard",
      intervals: [1, 3, 7, 15, 30, 60, 120],
      repeatInterval: 120
    };
  }
};

// src/review/ReviewView.ts
var import_obsidian2 = require("obsidian");
var REVIEW_VIEW_TYPE = "note-reviewer-view";
var ReviewView = class extends import_obsidian2.ItemView {
  constructor(leaf, reviewManager) {
    super(leaf);
    this.reviewManager = reviewManager;
  }
  getViewType() {
    return REVIEW_VIEW_TYPE;
  }
  getDisplayText() {
    return "Note Reviewer";
  }
  getIcon() {
    return "calendar-clock";
  }
  async onOpen() {
    await this.renderView();
    this.registerEvent(
      this.app.metadataCache.on("changed", () => {
        this.renderView();
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", () => {
        this.renderView();
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", () => {
        this.renderView();
      })
    );
  }
  async renderView() {
    const container = this.containerEl.children[1];
    container.empty();
    const header = container.createEl("h4", { text: "Due for Review" });
    header.addClass("note-reviewer-header");
    const dueNotes = this.reviewManager.getDueNotes();
    if (dueNotes.length === 0) {
      const emptyState = container.createEl("p", { text: "No notes to review today! \u{1F389}" });
      emptyState.addClass("note-reviewer-empty");
      return;
    }
    const todayStr = DateUtils.getTodayStr();
    const stageNotes = dueNotes.filter((n) => n.intervalIndex === 0);
    const todayNotes = dueNotes.filter((n) => n.intervalIndex > 0 && n.nextDate === todayStr);
    const overdueNotes = dueNotes.filter((n) => n.intervalIndex > 0 && (n.nextDate || "") < todayStr);
    const renderSection = (title, notes, defaultOpen = true) => {
      if (notes.length === 0)
        return;
      const detailsEl = container.createEl("details");
      if (defaultOpen) {
        detailsEl.setAttribute("open", "");
      }
      detailsEl.style.marginBottom = "16px";
      const summaryEl = detailsEl.createEl("summary", { text: `${title} (${notes.length})` });
      summaryEl.addClass("note-reviewer-subheader");
      summaryEl.style.cursor = "pointer";
      summaryEl.style.userSelect = "none";
      const listContainer = detailsEl.createDiv("note-reviewer-list");
      for (const item of notes) {
        this.renderReviewItem(listContainer, item);
      }
    };
    const order = this.reviewManager.settings.sectionOrder || ["Overdue", "Today", "Stage"];
    order.forEach((sectionName) => {
      if (sectionName === "Overdue")
        renderSection("Overdue", overdueNotes, true);
      else if (sectionName === "Today")
        renderSection("Today", todayNotes, true);
      else if (sectionName === "Stage")
        renderSection("Stage", stageNotes, true);
    });
  }
  renderReviewItem(parent, item) {
    const itemEl = parent.createDiv("note-reviewer-item");
    const titleEl = itemEl.createDiv("note-reviewer-title");
    titleEl.setText(item.file.basename);
    titleEl.onclick = async () => {
      await this.app.workspace.getLeaf(false).openFile(item.file);
    };
    const actionsEl = itemEl.createDiv("note-reviewer-actions");
    const doneBtn = actionsEl.createEl("button", { text: "Done" });
    doneBtn.addClass("mod-cta");
    doneBtn.onclick = async (e) => {
      e.stopPropagation();
      doneBtn.disabled = true;
      await this.reviewManager.markDone(item);
    };
    const skipBtn = actionsEl.createEl("button", { text: "Skip" });
    skipBtn.onclick = async (e) => {
      e.stopPropagation();
      skipBtn.disabled = true;
      await this.reviewManager.skipReview(item);
    };
    const postponeBtn = actionsEl.createEl("button", { text: "Postpone" });
    postponeBtn.onclick = async (e) => {
      e.stopPropagation();
      postponeBtn.disabled = true;
      await this.reviewManager.postponeReview(item);
    };
    const adjustBtn = actionsEl.createEl("button", { text: "Adjust" });
    adjustBtn.onclick = async (e) => {
      e.stopPropagation();
      adjustBtn.disabled = true;
      await this.reviewManager.adjustReview(item);
    };
    const doneSim = this.reviewManager.simulateDone(item);
    const adjustSim = this.reviewManager.getLowestLoadDay(item.file.path);
    const actionsInfoEl = itemEl.createDiv("note-reviewer-actions-info");
    actionsInfoEl.createSpan({ text: `Done -> ${doneSim.date} (+${doneSim.daysToAdd}d)` });
    actionsInfoEl.createSpan({ text: `Adjust -> ${adjustSim.date} (+${adjustSim.daysToAdd}d)` });
  }
};

// src/utils/FrontmatterUtils.ts
var FrontmatterUtils = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Get a specific property value from a file's frontmatter.
   */
  getProperty(file, key) {
    var _a;
    const cache = this.app.metadataCache.getFileCache(file);
    return (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a[key];
  }
  /**
   * Determine if a file has a review preset assigned.
   */
  getReviewPreset(file) {
    const value = this.getProperty(file, FRONTMATTER_KEYS.REVIEW);
    if (typeof value === "string" && value.trim().length > 0) {
      return value.trim();
    }
    return null;
  }
  /**
   * Update multiple frontmatter properties at once.
   */
  async updateProperties(file, properties) {
    await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
      for (const [key, value] of Object.entries(properties)) {
        if (value === null || value === void 0) {
          delete frontmatter[key];
        } else {
          frontmatter[key] = value;
        }
      }
    });
  }
};

// src/main.ts
var NoteReviewerPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.fmUtils = new FrontmatterUtils(this.app);
    this.reviewManager = new ReviewManager(this.app, this.settings, this.fmUtils);
    this.registerView(
      REVIEW_VIEW_TYPE,
      (leaf) => new ReviewView(leaf, this.reviewManager)
    );
    this.addRibbonIcon("calendar-clock", "Open Note Reviewer", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-review-view",
      name: "Open Review Pane",
      callback: () => {
        this.activateView();
      }
    });
    this.addCommand({
      id: "add-to-standard-review",
      name: "Add current note to standard review",
      callback: async () => {
        const file = this.app.workspace.getActiveFile();
        if (file) {
          await this.fmUtils.updateProperties(file, {
            [FRONTMATTER_KEYS.REVIEW]: "standard",
            [FRONTMATTER_KEYS.NEXT_DATE]: DateUtils.getTodayStr(),
            [FRONTMATTER_KEYS.INTERVAL_INDEX]: 0,
            [FRONTMATTER_KEYS.SKIP_COUNT]: 0
          });
        }
      }
    });
    this.addSettingTab(new SettingsTab(this.app, this));
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(REVIEW_VIEW_TYPE);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.reviewManager = new ReviewManager(this.app, this.settings, this.fmUtils);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(REVIEW_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({ type: REVIEW_VIEW_TYPE, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
};
